name: Create Review App Nextjs
on:
  pull_request:
    types: [reopened, opened, synchronize, edited]
    name: Create PR Env
jobs:
  create_or_update_pr_env:
    runs-on: ubuntu-latest
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BRANCH_NAME: ${{ github.head_ref }}
      SOURCE_DIR: "out"
      DEST_DIR: ${{ github.head_ref }}/${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Next
        run: npm install
      - name: Clean out directory
        run: rm -rf out
      - name: Change basePath
        run: |
          sed -i 's/\( *basePath:\).*/\1 "\/${{ github.head_ref }}\/${{ github.sha }}",/' next.config.js
          echo | cat next.config.js
      - name: Build Site
        run: npm run-script build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
  show-preview-url:
    runs-on: ubuntu-latest
    needs: [create_or_update_pr_env]
    steps:
      - uses: actions/checkout@v2
      - uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: Check out the preview here https://{{ secrets.AWS_CF_DOMAIN }}/${{ github.head_ref }}/${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
