name: Remove Review App

on:
  pull_request:
    types: [closed]

jobs:
  remove-from-s3:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_CF_DIST_ID: ${{ secrets.AWS_CF_DIST_ID }}
    steps:
      - name: Missing AWS Credentials
        if: ${{ !env.AWS_SECRET_ACCESS_KEY && !env.AWS_ACCESS_KEY_ID }}
        run: exit 1
      - name: Missing CloudFront Distribution ID
        if: ${{ !env.AWS_CF_DIST_ID }}
        run: exit 1
      - name: Missing S3 Bucket name
        if: ${{ !env.AWS_S3_BUCKET }}
        run: exit 1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Remove Review Apps from S3
        run: aws s3 rm s3://${{ env.AWS_S3_BUCKET }}/${{ github.head_ref }} --recursive
      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ env.AWS_CF_DIST_ID }} --paths /${{ github.head_ref }}/*
