name: Remove Review App

on:
  pull_request:
    types: [closed]

jobs:
  remove-from-s3:
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Remove Review Apps from S3
        run: aws s3 rm s3://${{ env.AWS_S3_BUCKET }}/${{ github.head_ref }} --recursive
      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths /${{ github.head_ref }}/*